ALTER TABLE "members" ADD COLUMN IF NOT EXISTS "empresa" TEXT;
ALTER TABLE "members" ADD COLUMN IF NOT EXISTS "ramoAtuacao" TEXT;
ALTER TABLE "members" ADD COLUMN IF NOT EXISTS "site" TEXT;
ALTER TABLE "members" ADD COLUMN IF NOT EXISTS "linkedin" TEXT;
